/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BusinessModelLayer.Proveedores;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author Carlos D
 */
public class frmMain extends javax.swing.JFrame {

    
    public frmMain() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagen/farma.png"));
        Image image =icon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){ g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        bSalir = new javax.swing.JMenuItem();
        mnCatalogos = new javax.swing.JMenu();
        bProductos = new javax.swing.JMenuItem();
        bFarmacias = new javax.swing.JMenuItem();
        bCategorias = new javax.swing.JMenuItem();
        bClientes = new javax.swing.JMenuItem();
        bContactos = new javax.swing.JMenuItem();
        bEstados = new javax.swing.JMenuItem();
        bLocalidades = new javax.swing.JMenuItem();
        bMunicipios = new javax.swing.JMenuItem();
        bProveedores = new javax.swing.JMenuItem();
        bUsuarios = new javax.swing.JMenuItem();
        bProveedoresPorductos = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnArchivo.setText("Archivo");

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(bSalir);

        jMenuBar1.add(mnArchivo);

        mnCatalogos.setText("Catalogos");

        bProductos.setText("Productos");
        bProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosActionPerformed(evt);
            }
        });
        mnCatalogos.add(bProductos);

        bFarmacias.setText("Farmacias");
        bFarmacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFarmaciasActionPerformed(evt);
            }
        });
        mnCatalogos.add(bFarmacias);

        bCategorias.setText("Categorias");
        bCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCategoriasActionPerformed(evt);
            }
        });
        mnCatalogos.add(bCategorias);

        bClientes.setText("Clientes");
        bClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientesActionPerformed(evt);
            }
        });
        mnCatalogos.add(bClientes);

        bContactos.setText("Contactos");
        bContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContactosActionPerformed(evt);
            }
        });
        mnCatalogos.add(bContactos);

        bEstados.setText("Estados");
        bEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadosActionPerformed(evt);
            }
        });
        mnCatalogos.add(bEstados);

        bLocalidades.setText("Localidades");
        bLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLocalidadesActionPerformed(evt);
            }
        });
        mnCatalogos.add(bLocalidades);

        bMunicipios.setText("Municipios");
        bMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMunicipiosActionPerformed(evt);
            }
        });
        mnCatalogos.add(bMunicipios);

        bProveedores.setText("Proveedores");
        bProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProveedoresActionPerformed(evt);
            }
        });
        mnCatalogos.add(bProveedores);

        bUsuarios.setText("Usuarios");
        bUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsuariosActionPerformed(evt);
            }
        });
        mnCatalogos.add(bUsuarios);

        bProveedoresPorductos.setText("Proveedores Productos");
        bProveedoresPorductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProveedoresPorductosActionPerformed(evt);
            }
        });
        mnCatalogos.add(bProveedoresPorductos);

        jMenuBar1.add(mnCatalogos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosActionPerformed
        frmProductos obj = new frmProductos();
        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);

    }//GEN-LAST:event_bProductosActionPerformed

    private void bFarmaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFarmaciasActionPerformed
        frmFarmacias obj = new frmFarmacias();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);

    }//GEN-LAST:event_bFarmaciasActionPerformed

    private void bCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCategoriasActionPerformed
        frmCategorias obj = new frmCategorias();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
    }//GEN-LAST:event_bCategoriasActionPerformed

    private void bClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientesActionPerformed
        frmClientes obj = new frmClientes();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
    }//GEN-LAST:event_bClientesActionPerformed

    private void bContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContactosActionPerformed
        frmContactos obj = new frmContactos();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
    }//GEN-LAST:event_bContactosActionPerformed

    private void bEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadosActionPerformed
        frmEstados obj = new frmEstados();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
    }//GEN-LAST:event_bEstadosActionPerformed

    private void bLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLocalidadesActionPerformed
        frmLocalidades obj = new frmLocalidades();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
    }//GEN-LAST:event_bLocalidadesActionPerformed

    private void bMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMunicipiosActionPerformed
        frmMunicipios obj = new frmMunicipios();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
    }//GEN-LAST:event_bMunicipiosActionPerformed

    private void bProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProveedoresActionPerformed
        frmProveedores obj = new frmProveedores();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
    }//GEN-LAST:event_bProveedoresActionPerformed

    private void bUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsuariosActionPerformed
        frmUsuarios obj = new frmUsuarios();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
    }//GEN-LAST:event_bUsuariosActionPerformed

    private void bProveedoresPorductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProveedoresPorductosActionPerformed
        frmProductoPorveedor obj = new frmProductoPorveedor();

        int x = (desktopPane.getWidth() / 2) - obj.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - obj.getHeight() / 2;
        desktopPane.add(obj);
        obj.setLocation(x, y);
        
    }//GEN-LAST:event_bProveedoresPorductosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bCategorias;
    private javax.swing.JMenuItem bClientes;
    private javax.swing.JMenuItem bContactos;
    private javax.swing.JMenuItem bEstados;
    private javax.swing.JMenuItem bFarmacias;
    private javax.swing.JMenuItem bLocalidades;
    private javax.swing.JMenuItem bMunicipios;
    private javax.swing.JMenuItem bProductos;
    private javax.swing.JMenuItem bProveedores;
    private javax.swing.JMenuItem bProveedoresPorductos;
    private javax.swing.JMenuItem bSalir;
    private javax.swing.JMenuItem bUsuarios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenu mnCatalogos;
    // End of variables declaration//GEN-END:variables
}
