/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BusinessModelLayer.Contactos;
import BusinessModelLayer.Localidades;
import BusinessModelLayer.Municipios;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos D
 */
public class frmNContacto extends javax.swing.JDialog {

    private int idContacto;
    Contactos contacto = new Contactos();
    Localidades localidad = new Localidades();
    Municipios municipio = new Municipios();

    public frmNContacto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public frmNContacto() {
        initComponents();
        setLocationRelativeTo(null);

        for (int i = 0; i < municipio.GetAllModel().getRowCount(); i++) {
            cbMunicipio.addItem("" + municipio.GetAllModel().getValueAt(i, 1));
        }
        int idMunicipio = 0;

        for (int i = 0; i < municipio.GetAllModel().getRowCount(); i++) {
            if (cbMunicipio.getSelectedItem().equals(municipio.GetAllModel().getValueAt(i, 1))) {
                idMunicipio = (int) municipio.GetAllModel().getValueAt(i, 0);
                System.out.println(municipio.GetAllModel().getValueAt(i, 0));
            }
        }

        cbLocalidad.removeAllItems();
        for (int i = 0; i < localidad.GetAllModel().getRowCount(); i++) {

            if (localidad.GetAllModel().getValueAt(i, 2).equals(idMunicipio)) {
                cbLocalidad.addItem(localidad.GetAllModel().getValueAt(i, 1).toString());
            }
        }

    }

    public frmNContacto(int idContacto) {
        initComponents();
        setLocationRelativeTo(null);
        this.idContacto = idContacto;
        contacto.setIdContacto(idContacto);;
        contacto.GetById();

        tCodigoPostal.setText("" + contacto.getCodigoPostal());
        tTelefono.setText(contacto.getTelefono());
        tCalle.setText(contacto.getCalle());
        int idMunicipio = 0;
        
        for (int i = 0; i < municipio.GetAllModel().getRowCount(); i++) {
            cbMunicipio.addItem(municipio.GetAllModel().getValueAt(i, 1).toString());

            if (contacto.getIdMunicipio() == (int) municipio.GetAllModel().getValueAt(i, 0)) {
                cbMunicipio.setSelectedItem("" + municipio.GetAllModel().getValueAt(i, 1));
                idMunicipio = (int) municipio.GetAllModel().getValueAt(i, 0);
            }
        }
        
        
        cbLocalidad.removeAllItems();
        for (int i = 0; i < localidad.GetAllModel().getRowCount(); i++) {

            if (localidad.GetAllModel().getValueAt(i, 2).equals(idMunicipio)) {
                cbLocalidad.addItem(localidad.GetAllModel().getValueAt(i, 1).toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCancelar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tCodigoPostal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbLocalidad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tCalle = new javax.swing.JTextField();
        Municipio = new javax.swing.JLabel();
        cbMunicipio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Postal");

        jLabel2.setText("Telefono");

        jLabel3.setText("Localidad");

        jLabel4.setText("Calle");

        Municipio.setText("Municipio");

        cbMunicipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMunicipioItemStateChanged(evt);
            }
        });
        cbMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbMunicipioMouseReleased(evt);
            }
        });
        cbMunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbMunicipioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(bGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(Municipio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCodigoPostal)
                            .addComponent(tTelefono)
                            .addComponent(cbLocalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tCalle)
                            .addComponent(cbMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Municipio)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bGuardar)
                    .addComponent(bCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        int idLocalidad = 0;

        if (cbLocalidad.getSelectedIndex() >= 0) {
            
            for (int i = 0; i < localidad.GetAllModel().getRowCount(); i++) {
                if (cbLocalidad.getSelectedItem().equals(localidad.GetAllModel().getValueAt(i, 1))) {
                    idLocalidad = (int) localidad.GetAllModel().getValueAt(i, 0);
                    System.out.println(localidad.GetAllModel().getValueAt(i, 0));
                }
            }
        }

        int idMunicipio = 0;

        for (int i = 0; i < municipio.GetAllModel().getRowCount(); i++) {
            if (cbMunicipio.getSelectedItem().equals(municipio.GetAllModel().getValueAt(i, 1))) {
                idMunicipio = (int) municipio.GetAllModel().getValueAt(i, 0);
                System.out.println(municipio.GetAllModel().getValueAt(i, 0));
            }
        }

        if (contacto.getIdContacto() > 0) {
            contacto.setCalle(tCalle.getText());
            contacto.setCodigoPostal(Integer.parseInt(tCodigoPostal.getText()));
            contacto.setTelefono(tTelefono.getText());
            contacto.setIdLocalidad(idLocalidad);
            contacto.setIdMunicipio(idMunicipio);

            if (contacto.Update()) {
                JOptionPane.showMessageDialog(null, "Contacto actualizado correctamente");
                this.dispose();
            }

        } else {
            if (new Contactos(0, tCalle.getText(),
                    Integer.parseInt(tCodigoPostal.getText()),
                    tTelefono.getText(),
                    idLocalidad,
                    idMunicipio).Add()) {
                JOptionPane.showMessageDialog(this, "Contacto agregado correctamente");
                this.dispose();
            }
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void cbMunicipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMunicipioItemStateChanged
        int idMunicipio = 0;

        cbLocalidad.removeAllItems();

        for (int i = 0; i < municipio.GetAllModel().getRowCount(); i++) {
            if (cbMunicipio.getSelectedItem().equals(municipio.GetAllModel().getValueAt(i, 1))) {
                idMunicipio = (int) municipio.GetAllModel().getValueAt(i, 0);
                System.out.println(municipio.GetAllModel().getValueAt(i, 0));
            }
        }

        for (int i = 0; i < localidad.GetAllModel().getRowCount(); i++) {

            if (localidad.GetAllModel().getValueAt(i, 2).equals(idMunicipio)) {
                cbLocalidad.addItem(localidad.GetAllModel().getValueAt(i, 1).toString());
            }
        }
    }//GEN-LAST:event_cbMunicipioItemStateChanged

    private void cbMunicipioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbMunicipioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMunicipioKeyReleased

    private void cbMunicipioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMunicipioMouseReleased

    }//GEN-LAST:event_cbMunicipioMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmNContacto dialog = new frmNContacto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Municipio;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JComboBox<String> cbLocalidad;
    private javax.swing.JComboBox<String> cbMunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tCalle;
    private javax.swing.JTextField tCodigoPostal;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
